/**
 * PR comment builder for TestivAI visual reports
 */

import { ResultsData, SnapshotResult, SnapshotImageUrls } from './types';

const UPSERT_MARKER = '<!-- testivai-visual-report -->';

/**
 * Format the diff percentage for a snapshot, accepting both the new
 * (`diffPercent`) and older (`diffPercentage`) field names.
 */
function formatDiffPercent(snapshot: SnapshotResult): string {
  const value = snapshot.diffPercent ?? snapshot.diffPercentage ?? 0;
  return value.toFixed(2);
}

/**
 * Render the DOM noise hint inside the <details> body for a changed
 * snapshot. Mirrors the witness HTML report wording so reviewers see
 * the same signal in the PR comment.
 *
 * Returns empty string when the snapshot has no DOM data — better than
 * a confusing "no signal available" line.
 */
function renderDomHintMarkdown(snapshot: SnapshotResult): string {
  if (!snapshot.dom) return '';
  if (snapshot.dom.noiseHint) {
    return `> 💡 **DOM unchanged** — pixel diff is likely render noise (anti-aliasing, font hinting).\n\n`;
  }
  const s = snapshot.dom.summary;
  if (!s) return '';
  const parts: string[] = [];
  if (s.added > 0) parts.push(`${s.added} added`);
  if (s.removed > 0) parts.push(`${s.removed} removed`);
  if (s.attributeChanges > 0) parts.push(`${s.attributeChanges} attribute change${s.attributeChanges === 1 ? '' : 's'}`);
  return `> 🧱 **DOM changed** — ${parts.join(', ') || 'structural difference'}.\n\n`;
}

/**
 * Render a 3-column image comparison table (baseline | current | diff).
 * Only columns with a URL are included — so a diff-only upload shows 1 col.
 * Returns empty string if no URLs are provided.
 */
function renderImageTable(images: SnapshotImageUrls): string {
  const cols: string[] = [];
  const imgs: string[] = [];

  if (images.baseline) {
    cols.push('Baseline');
    imgs.push(`![baseline](${images.baseline})`);
  }
  if (images.current) {
    cols.push('Current');
    imgs.push(`![current](${images.current})`);
  }
  if (images.diff) {
    cols.push('Diff');
    imgs.push(`![diff](${images.diff})`);
  }

  if (cols.length === 0) return '';

  return `| ${cols.join(' | ')} |
| ${cols.map(() => ':---:').join(' | ')} |
| ${imgs.join(' | ')} |

`;
}

/**
 * Build markdown PR comment from results.
 *
 * @param results   Parsed results.json
 * @param imageUrls Optional map of snapshot name → uploaded image URLs.
 *                  When provided, a before/current/diff image table is
 *                  rendered inside each changed-snapshot <details> block.
 *                  If image upload failed for a snapshot, pass undefined or
 *                  omit the entry — the comment degrades to text-only.
 */
export function buildComment(
  results: ResultsData,
  imageUrls?: Map<string, SnapshotImageUrls>,
): string {
  const { summary, snapshots } = results;

  // Header with emoji summary
  const passedEmoji = summary.passed > 0 ? '✅' : '⬜';
  const changedEmoji = summary.changed > 0 ? '⚠️' : '⬜';
  const newEmoji = summary.newSnapshots > 0 ? '🆕' : '⬜';

  const summaryLine = `${passedEmoji} **${summary.passed} passed** · ${changedEmoji} **${summary.changed} changed** · ${newEmoji} **${summary.newSnapshots} new**`;

  let comment = `${UPSERT_MARKER}

### 🔍 TestivAI Visual Report

${summaryLine}

**Total snapshots:** ${summary.total}

`;

  // Show changed snapshots with approve command + DOM noise hint + diff images
  const changedSnapshots = snapshots.filter(s => s.status === 'changed');
  if (changedSnapshots.length > 0) {
    comment += '#### Changed Snapshots\n\n';
    for (const snapshot of changedSnapshots) {
      const diffPercent = formatDiffPercent(snapshot);
      const domHint = renderDomHintMarkdown(snapshot);
      const images = imageUrls?.get(snapshot.name);
      const imageTable = images ? renderImageTable(images) : '';

      comment += `<details>
<summary><code>${snapshot.name}</code> — ${diffPercent}% different</summary>

${domHint}${imageTable}\`\`\`bash
npx testivai approve "${snapshot.name}"
# Or approve all changed snapshots:
npx testivai approve --all
\`\`\`
</details>

`;
    }
  }

  // Show new snapshots
  const newSnapshots = snapshots.filter(s => s.status === 'new');
  if (newSnapshots.length > 0) {
    comment += '#### New Snapshots\n\n';
    for (const snapshot of newSnapshots) {
      comment += `- \`${snapshot.name}\`\n`;
    }
    comment += '\n';
  }

  // Footer with report link
  comment += '---\n*Generated by [TestivAI](https://testiv.ai)*\n';

  return comment;
}

/**
 * Build simple message for empty results
 */
export function buildEmptyComment(): string {
  return `${UPSERT_MARKER}

### 🔍 TestivAI Visual Report

No visual snapshots were captured in this test run.

---
*Generated by [TestivAI](https://testiv.ai)*
`;
}
